# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# https://docs.gradle.org/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Configure-on-demand
org.gradle.configureondemand=false

# AndroidX
android.enableJetifier=true
android.useAndroidX=true

# Non-transitive R classes
android.nonTransitiveRClass=true

# Disable file system watching (Alpine/musl compatibility)
org.gradle.vfs.watch=false
